Moved MSOY to the NNWO.

diff --git a/bin/msoy b/bin/msoy
--- a/bin/msoy
+++ b/bin/msoy
@@ -12,13 +12,16 @@ fi
 
 MSOY_HOME=`dirname $0`/..
 MSOY_HOME=`cd $MSOY_HOME ; pwd`
-if [ ! -f $MSOY_HOME/server.conf ]; then
+if [ ! -f $MSOY_HOME/dist/server.conf ]; then
     echo "Unable to infer MSOY_HOME. No server.conf file?"
     exit 1
 fi
 
 # Read in our configuration
-. $MSOY_HOME/server.conf
+. $MSOY_HOME/dist/server.conf
+
+# Use our hostname as a node identifier for log files and such
+HOSTNAME=`hostname`
 
 # Let's blow that file descriptor limit wide open baby!
 ulimit -n 4096
@@ -30,77 +33,67 @@ ulimit -d 1572864
 case "$1" in
   start)
         # Make sure msoyrespawn is not currently running
-        for NODE in $NODES; do
-            if [ -f $MSOY_HOME/run/respawn-$NODE.pid ]; then
-                echo "msoyrespawn appears to be already running for $NODE."
-                echo "Run '$0 stop' to stop it first."
-                exit 1
-            fi
-        done
+        if [ -f $MSOY_HOME/run/respawn-$HOSTNAME.pid ]; then
+            echo "msoyrespawn appears to be already running for $HOSTNAME."
+            echo "Run '$0 stop' to stop it first."
+            exit 1
+        fi
 
         # Make sure there are no hung MetaSOY server processes
-        for NODE in $NODES; do
-            SERVER_PIDFILE=$MSOY_HOME/run/server-$NODE.pid
-            if [ -f $SERVER_PIDFILE ]; then
-                PID=`cat $SERVER_PIDFILE`
-                RPIDS=`ps auxww | grep " $PID " | grep java | awk '{ print $2 }' | \
-                    sort -n | head -1`
-                if [ ! -z "$RPIDS" ]; then
-                    echo "WARNING: A $NODE MsoyServer process is currently running."
-                    echo "If it has failed and you wish to forcibly restart it, please"
-                    echo "execute the following commands:"
-                    echo ""
-                    echo "% kill -QUIT $RPIDS"
-                    echo "% kill -KILL $RPIDS"
-                    echo ""
-                    echo "And then rerun this script."
-                    exit 255
-                fi
+        SERVER_PIDFILE=$MSOY_HOME/run/server-$HOSTNAME.pid
+        if [ -f $SERVER_PIDFILE ]; then
+            PID=`cat $SERVER_PIDFILE`
+            RPIDS=`ps auxww | grep " $PID " | grep java | awk '{ print $2 }' | \
+                sort -n | head -1`
+            if [ ! -z "$RPIDS" ]; then
+                echo "WARNING: A $HOSTNAME MsoyServer process is currently running."
+                echo "If it has failed and you wish to forcibly restart it, please"
+                echo "execute the following commands:"
+                echo ""
+                echo "% kill -QUIT $RPIDS"
+                echo "% kill -KILL $RPIDS"
+                echo ""
+                echo "And then rerun this script."
+                exit 255
             fi
-        done
+        fi
 
         # Go ahead and start things up
-        for NODE in $NODES; do
-            DAEMON=$MSOY_HOME/bin/msoyrespawn
-            RESPAWN_PIDFILE=$MSOY_HOME/run/respawn-$NODE.pid
-            SERVER_PIDFILE=$MSOY_HOME/run/server-$NODE.pid
-            LOGFILE=$MSOY_HOME/log/respawn-$NODE.log
-            echo -n "Starting $DAEMON: "
-            touch $RESPAWN_PIDFILE $LOGFILE
-            $DAEMON $NODE $RESPAWN_PIDFILE $SERVER_PIDFILE >>$LOGFILE 2>&1 </dev/null &
-            echo "started."
-        done
+        DAEMON=$MSOY_HOME/bin/msoyrespawn
+        RESPAWN_PIDFILE=$MSOY_HOME/run/respawn-$HOSTNAME.pid
+        SERVER_PIDFILE=$MSOY_HOME/run/server-$HOSTNAME.pid
+        LOGFILE=$MSOY_HOME/log/respawn-$HOSTNAME.log
+        echo -n "Starting $DAEMON: "
+        touch $RESPAWN_PIDFILE $LOGFILE
+        $DAEMON $HOSTNAME $RESPAWN_PIDFILE $SERVER_PIDFILE >>$LOGFILE 2>&1 </dev/null &
+        echo "started."
         ;;
 
   stop)
-        for NODE in $NODES ; do
-            RESPAWN_PIDFILE=$MSOY_HOME/run/respawn-$NODE.pid
-            SERVER_PIDFILE=$MSOY_HOME/run/server-$NODE.pid
-            if [ ! -f $RESPAWN_PIDFILE ]; then
-                echo "No $RESPAWN_PIDFILE exists. Is msoyrespawn running?"
-            else
-                echo -n "Shutting down msoy node $NODE, "
-                kill -INT `cat $SERVER_PIDFILE`
-                echo -n "msoyrespawn: "
-                kill `cat $RESPAWN_PIDFILE`
-                echo "stopped."
-                rm -f $RESPAWN_PIDFILE $SERVER_PIDFILE
-            fi
-        done
+        RESPAWN_PIDFILE=$MSOY_HOME/run/respawn-$HOSTNAME.pid
+        SERVER_PIDFILE=$MSOY_HOME/run/server-$HOSTNAME.pid
+        if [ ! -f $RESPAWN_PIDFILE ]; then
+            echo "No $RESPAWN_PIDFILE exists. Is msoyrespawn running?"
+        else
+            echo -n "Shutting down msoy node $HOSTNAME, "
+            kill -INT `cat $SERVER_PIDFILE`
+            echo -n "msoyrespawn: "
+            kill `cat $RESPAWN_PIDFILE`
+            echo "stopped."
+            rm -f $RESPAWN_PIDFILE $SERVER_PIDFILE
+        fi
         ;;
 
   unspawn)
-        for NODE in $NODES ; do
-            RESPAWN_PIDFILE=$MSOY_HOME/run/respawn-$NODE.pid
-            if [ ! -f $RESPAWN_PIDFILE ]; then
-                echo "No $RESPAWN_PIDFILE exists. Is msoyrespawn running?"
-            else
-                echo -n "Shutting down msoyrespawn: "
-                kill `cat $RESPAWN_PIDFILE`
-                echo "stopped."
-                rm -f $RESPAWN_PIDFILE
-            fi
-        done
+        RESPAWN_PIDFILE=$MSOY_HOME/run/respawn-$HOSTNAME.pid
+        if [ ! -f $RESPAWN_PIDFILE ]; then
+            echo "No $RESPAWN_PIDFILE exists. Is msoyrespawn running?"
+        else
+            echo -n "Shutting down msoyrespawn: "
+            kill `cat $RESPAWN_PIDFILE`
+            echo "stopped."
+            rm -f $RESPAWN_PIDFILE
+        fi
         ;;
 
   restart)
