Bring the msoy scripts along with the rest of the games so they can be restarted etc.

diff --git a/bin/msoy b/bin/msoy
--- a/bin/msoy
+++ b/bin/msoy
@@ -4,6 +4,12 @@
 #
 # Startup script for the MetaSOY game server.
 
+WHOAMI=`whoami`
+if [ "$WHOAMI" != "root" ]; then
+    echo "This script must be run as root."
+    exit 255
+fi
+
 MSOY_HOME=`dirname $0`/..
 MSOY_HOME=`cd $MSOY_HOME ; pwd`
 if [ ! -f $MSOY_HOME/server.conf ]; then
@@ -16,7 +22,7 @@ fi
 
 # # Make sure someone running things as root didn't booch the permissions on
 # # the bundles
-# BFILE=/tmp/booched.txt
+# BFILE=$MSOY_HOME/run/booched.txt
 # find $MSOY_HOME/rsrc -user root > $BFILE
 # if [ -s "$BFILE" ]; then
 #     cat $BFILE | xargs chown -R $MSOY_USER
@@ -30,68 +36,69 @@ ulimit -n 4096
 ulimit -d 1572864
 
 DAEMON=$MSOY_HOME/bin/msoyrespawn
-PIDFILE=$MSOY_HOME/run/msoyrespawn.pid
+RESPAWN_PIDFILE=$MSOY_HOME/run/msoyrespawn.pid
+SERVER_PIDFILE=$MSOY_HOME/run/msoyserver.pid
+LOGFILE=$MSOY_HOME/log/msoyrespawn.log
 
 # See how we were called
 case "$1" in
   start)
         # Make sure msoyrespawn is not currently running
-	if [ -f $PIDFILE ]; then
+	if [ -f $RESPAWN_PIDFILE ]; then
 	    echo "msoyrespawn appears to be already running."
             echo "Run '$0 stop' to stop it first."
 	    exit 1
 	fi
         # Make sure there are no hung MetaSOY server processes
-        RPIDS=`ps auxww | grep MsoyServer | grep java | \
-            awk '{ print $2 }' | sort -n | head -1`
-        if [ ! -z "$RPIDS" ]; then
-            echo "WARNING: An MsoyServer process is currently running."
-            echo "If it has failed and you wish to forcibly restart it, please"
-            echo "execute the following commands:"
-            echo ""
-            echo "% kill -QUIT $RPIDS"
-            echo "% kill -KILL $RPIDS"
-            echo ""
-            echo "And then rerun this script."
-            exit 255
+        if [ -f $SERVER_PIDFILE ]; then
+            PID=`cat $SERVER_PIDFILE`
+            RPIDS=`ps auxww | grep " $PID " | grep java | awk '{ print $2 }' | sort -n | head -1`
+            if [ ! -z "$RPIDS" ]; then
+                echo "WARNING: An MsoyServer process is currently running."
+                echo "If it has failed and you wish to forcibly restart it, please"
+                echo "execute the following commands:"
+                echo ""
+                echo "% kill -QUIT $RPIDS"
+                echo "% kill -KILL $RPIDS"
+                echo ""
+                echo "And then rerun this script."
+                exit 255
+            fi
         fi
         # Go ahead and start things up
         echo -n "Starting $DAEMON: "
-        touch $PIDFILE
-        chown $MSOY_USER $PIDFILE
-        su - $MSOY_USER -c "$DAEMON $PIDFILE" >/tmp/startmsoy.log \
-            2>&1 </dev/null &
+        touch $RESPAWN_PIDFILE $LOGFILE
+        chown $MSOY_USER $RESPAWN_PIDFILE $LOGFILE
+        su - $MSOY_USER -c "$DAEMON $RESPAWN_PIDFILE $SERVER_PIDFILE" >$LOGFILE 2>&1 </dev/null &
         echo "started."
         ;;
 
   stop)
-	if [ ! -f $PIDFILE ]; then
-	    echo "No $PIDFILE exists. Is msoyrespawn running?"
+	if [ ! -f $RESPAWN_PIDFILE ]; then
+	    echo "No $RESPAWN_PIDFILE exists. Is msoyrespawn running?"
 	    exit 1
 	fi
         echo -n "Shutting down msoy, "
-        $MSOY_HOME/bin/msoyrestart
+        kill -INT `cat $SERVER_PIDFILE`
         echo -n "msoyrespawn: "
-        kill `cat $PIDFILE`
+        kill `cat $RESPAWN_PIDFILE`
         echo "stopped."
-        rm -f $PIDFILE
+        rm -f $RESPAWN_PIDFILE $SERVER_PIDFILE
         ;;
 
   unspawn)
-	if [ ! -f $PIDFILE ]; then
-	    echo "No $PIDFILE exists. Is msoyrespawn running?"
+	if [ ! -f $RESPAWN_PIDFILE ]; then
+	    echo "No $RESPAWN_PIDFILE exists. Is msoyrespawn running?"
 	    exit 1
 	fi
         echo -n "Shutting down msoyrespawn: "
-        kill `cat $PIDFILE`
+        kill `cat $RESPAWN_PIDFILE`
         echo "stopped."
-        rm -f $PIDFILE
+        rm -f $RESPAWN_PIDFILE
         ;;
 
   restart)
-        echo -n "Restarting msoy server: "
-        $MSOY_HOME/bin/msoyrestart
-        echo "restarted."
+        echo -n "Restart the server using the etc/rc.d script." 
         exit 1
         ;;
 
